### ISSUE TITLE
Updating speed mod, willing to help!

### ISSUE THREAD

**Issue by almenjonatan** [ddiera/TFM_speedmod#13]
Hi! 

I am in the works creating another mod for TFM. Since the latest update your mod is not 
working as expected. I wonder if it would be possible to get in contact with you to get a brief overview of
what methods in the code you did modify to achieve fast animations! 

feel free to contact me  at almen.jonatan@gmail.com

**Comment by ddiera** [comment]
Appreciate the offer.

Unfortunately I don't keep a detailed documentation of the code changes, only top-level description which is available in the readme.
I trust you have found about the relevant classes already in the meantime. :)
